### ISSUE TITLE
adding a raster crashes mask plugin

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#31]
in dev version May 26, 2015, adding a raster layer throws following error
'
Une erreur est apparue lors de l'exécution du code Python :

Traceback (most recent call last):
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 226, in on_current_layer_changed
    layer.selectionChanged.connect( self.on_current_layer_selection_changed )
AttributeError: 'QgsRasterLayer' object has no attribute 'selectionChanged'

Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Version de QGIS :
2.8.2-Wien Wien, 1b929ef

Chemin vers Python : ['U:/OSGEO4~1/apps/qgis/./python/plugins\\processing', 'U:/OSGEO4~1/apps/qgis/./python', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgis28dev/python', u'W:\\GIT_DEPOTS\\EasyCustomLabeling', u'W:\\GIT_DEPOTS\\mask', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgis28dev/python/plugins', 'U:/OSGEO4~1/apps/qgis/./python/plugins', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'U:\\OSGEO4~1\\apps\\orfeotoolbox\\python', 'U:\\OSGEO4~1\\bin', 'U:\\OSGEO4~1\\bin\\python27.zip', 'U:\\OSGEO4~1\\apps\\Python27\\DLLs', 'U:\\OSGEO4~1\\apps\\Python27\\lib', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\plat-win', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\lib-tk', 'U:\\OSGEO4~1\\apps\\Python27', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\owslib-0.7.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\setuptools-5.4.1-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\shapely-1.2.18-py2.7-win-amd64.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\PIL', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgis28dev/python', 'U:\\OSGEO4~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'R:/Espace_Correspondants_SIG/Espace_Travail/Reseau_Donnees_Connaissance/CONSULTATION_PDOM2014']
'

**Comment by haubourg** [comment]
after that error, updating the mask is broken:
Une erreur est apparue lors de l'exécution du code Python :


Traceback (most recent call last):
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 528, in run
    self.update_menus()
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 537, in update_menus
    self.on_current_layer_changed( self.iface.activeLayer() )
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 224, in on_current_layer_changed
    self.old_active_layer.selectionChanged.disconnect( self.on_current_layer_selection_changed )
TypeError: pyqtSignal must be bound to a QObject, not 'QgsVectorLayer'

**Comment by haubourg** [comment]
after #32 still a error message when adding a raster:

Traceback (most recent call last):
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismasterdev\python\mask\aeag_mask.py", line 226, in on_current_layer_changed
    layer.selectionChanged.connect( self.on_current_layer_selection_changed )
AttributeError: 'QgsRasterLayer' object has no attribute 'selectionChanged'

**Comment by haubourg** [comment]
@mhugo : one more, when moving raster layer in map registry:
Une erreur est apparue lors de l'exécution du code Python :


Traceback (most recent call last):
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 227, in on_current_layer_changed
    self.old_active_layer.selectionChanged.disconnect( self.on_current_layer_selection_changed )
TypeError: pyqtSignal must be bound to a QObject, not 'QgsVectorLayer'


Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


Version de QGIS :
2.8.2-Wien Wien, 1b929ef

Chemin vers Python : ['U:/OSGEO4~1/apps/qgis/./python/plugins\\processing', 'U:/OSGEO4~1/apps/qgis/./python', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgis28dev/python', u'W:\\GIT_DEPOTS\\EasyCustomLabeling', u'W:\\GIT_DEPOTS\\mask', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgis28dev/python/plugins', 'U:/OSGEO4~1/apps/qgis/./python/plugins', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'U:\\OSGEO4~1\\apps\\orfeotoolbox\\python', 'U:\\OSGEO4~1\\bin', 'U:\\OSGEO4~1\\bin\\python27.zip', 'U:\\OSGEO4~1\\apps\\Python27\\DLLs', 'U:\\OSGEO4~1\\apps\\Python27\\lib', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\plat-win', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\lib-tk', 'U:\\OSGEO4~1\\apps\\Python27', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\owslib-0.7.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\setuptools-5.4.1-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\shapely-1.2.18-py2.7-win-amd64.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\PIL', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgis28dev/python', 'U:\\OSGEO4~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'V:/temp_user/mask']
