### ISSUE TITLE
calling mask from do_mask, then calling mask from mask button raises an error

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#42]
Just call mask from do_mask (from another plugin here) raises an error:

`2015-12-02T10:29:10    1   Traceback (most recent call last):
              File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 541, in run
                on_applied_()
              File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 532, in on_applied_
                new_layer = self.apply_mask_parameters( self.layer, parameters, keep_layer = keep_layer )
              File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 482, in apply_mask_parameters
                pr.changeGeometryValues( {fid: parameters.geometry} )
            TypeError: QgsVectorDataProvider.changeGeometryValues(dict-of-qint64-QgsGeometry): argument 1 has unexpected type 'dict'
`

**Comment by mhugo** [comment]
I failed to reproduce.
