### ISSUE TITLE
QGIS 2.6.1 raises error with mask 1.5

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#51]
``
Impossible de charger l'extension mask provoque une erreur lors de l'appel de sa méthode initGui()

Traceback (most recent call last):
  File "U:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 217, in startPlugin
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 214, in initGui
    self.iface.mapCanvas().currentLayerChanged.connect( self.on_current_layer_changed )
AttributeError: 'QgsMapCanvas' object has no attribute 'currentLayerChanged'
``

**Comment by haubourg** [comment]
Crashes QGIS occur every time too.

**Comment by haubourg** [comment]
fixed by version 1.5.1
