### ISSUE TITLE
Couldn't load plugin 'mask' due to an error when calling its initGui() method 

### ISSUE THREAD

**Issue by Radler55** [aeag/mask#69]
Couldn't load plugin 'mask' due to an error when calling its initGui() method 

TypeError: QgsLayoutManager.layoutByName(): argument 1 has unexpected type 'QgsPrintLayout' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 345, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/david.lane/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mask\aeag_mask.py", line 226, in initGui
    self.on_layout_added(layout)
  File "C:/Users/david.lane/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mask\aeag_mask.py", line 349, in on_layout_added
    layout = QgsProject.instance().layoutManager().layoutByName(layoutName)
TypeError: QgsLayoutManager.layoutByName(): argument 1 has unexpected type 'QgsPrintLayout'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.3-Girona Girona, 8a899c8758 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/david.lane/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/david.lane/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\Pythonwin
C:/Users/david.lane/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\david.lane\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
R:/HSE Department/Environment/GIS

**Comment by Radler55** [comment]
Duplicate of 66
