### ISSUE TITLE
Locale symbol for decimal value

### ISSUE THREAD

**Issue by djes** [aeag/mask#75]
Hi, as a french, locale symbol for decimal is ',', not the dot. But if use it, for example in units field, I get the following python error :
ValueError: could not convert string to float: '1,5' 
Traceback (most recent call last):
  File "D:/Users/jbenoist/AppData/Roaming/QGIS/QGIS3\profiles\djes/python/plugins\mask\maindialog.py", line 289, in accept
    self.apply()
  File "D:/Users/jbenoist/AppData/Roaming/QGIS/QGIS3\profiles\djes/python/plugins\mask\maindialog.py", line 294, in apply
    self.update_parameters_from_ui(self.parameters)
  File "D:/Users/jbenoist/AppData/Roaming/QGIS/QGIS3\profiles\djes/python/plugins\mask\maindialog.py", line 134, in update_parameters_from_ui
    parameters.buffer_units = float(self.ui.bufferUnits.text() or 0)
ValueError: could not convert string to float: '1,5'

The bad is that I cannot use the US dot, the keyboard being limited to locale keys...

**Comment by xcaeag** [comment]
Thanks, a new release is coming soon ...
