### ISSUE TITLE
Unable to install it :  AttributeError: 'aeag_mask' object has no attribute 'iface'

### ISSUE THREAD

**Issue by Doctor-Who** [aeag/mask#77]
QGIS 3.8.3
OS : Linux

Error message during installation : 

```
AttributeError: 'aeag_mask' object has no attribute 'iface' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/qgis/utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "/home/nrochard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mask/aeag_mask.py", line 191, in initGui
    self.iface.mainWindow())
AttributeError: 'aeag_mask' object has no attribute 'iface'
```

Thanks

**Comment by pedrogeo** [comment]
Hi, I have the same error message on Windows 10, Qgis 3.10.1, Python 3.7.0 during installation.

Pierre

**Comment by xcaeag** [comment]
Thanks,
The absence of 'locale' probably behind the bug. A new version is coming soon.
